#server config
server:
  port: 80
spring:
  application:
    name: security-demo
  http:
      encoding:
        force: true
  redis:
     host: 10.6.56.29
#     password: sunniwell
     database: 3
  datasource:
      druid:
          url: jdbc:postgresql://127.0.0.1:5432/data
          username: root
          password: 123456
          driver-class-name: org.postgresql.Driver
          initial-size: 5
          min-idle: 6
          max-active: 20
          max-wait: 60000
          time-between-eviction-runs-millis: 60000
          min-evictable-idle-time-millis: 300000
          validation-query: SELECT 1
          test-while-idle: true
          test-on-borrow: false
          test-on-return: false
          pool-prepared-statements: true
          max-pool-prepared-statement-per-connection-size: 20
          filters: stat,wall,log4j
          connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000

  thymeleaf:
      prefix: classpath:/page/
      suffix: .html
      cache: false
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update



system:
#客户端配置
  client:
    clients[0]:
      clientId: lvhaibao
      clientSecret: 123456
    clients[1]:
      clientId: lhb
      clientSecret: 123456
    clients[2]:
      clientId: app
      clientSecret: app
  social:
    qq:
      app-id: xxxx
      app-secret: xxxx
      providerId: callback.do

    filterProcessesUrl: /qqLogin
    weixin:
      app-id: xxxx
      app-secret: xxxxx
